version: '2'
services:
  api_server:
      build:
        context: ./
        dockerfile: ./Dockerfile-dev
      volumes:
        - ./:/usr/src/app
      ports:
        - "localhost:8001:8001"
      environment:
        MONGO_HOST: "mongo"
        MONGO_USERNAME: ""
        MONGO_PASSWORD: ""
        MONGO_DBNAME: "development"
        DEVELOPMENT: "true"
  mongo:
    image: mongo:3.2
    volumes:
      - mongoDB:/data/db

volumes:
  mongoDB: {}
